services:
  waha:
    image: devlikeapro/waha:latest
    platform: linux/amd64
    environment:
      WHATSAPP_DEFAULT_ENGINE: GOWS
      WHATSAPP_HOOK_EVENTS: message
      WAHA_NO_API_KEY: true
      WAHA_DASHBOARD_NO_PASSWORD: true
      WHATSAPP_SWAGGER_NO_PASSWORD: true
    volumes:
    - waha_sessions:/app/.sessions
    - waha_media:/app/.media
    ports:
    - "3000:3000"